# Generated by Django 6.0.3 on 2026-03-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Содержимое (Plain Text)')),
                ('html_message', models.TextField(blank=True, help_text='Опционально. Если заполнено, отправится красивое HTML письмо.', verbose_name='Содержимое (HTML)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('sent', 'Отправлена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='Запланированное время')),
                ('recipients', models.ManyToManyField(limit_choices_to={'is_active': True}, to='mailer.client', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='SendingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('status', models.BooleanField(default=False, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.client', verbose_name='Клиент')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.newsletter', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог отправки',
                'verbose_name_plural': 'Логи отправок',
            },
        ),
    ]
