# Generated by Django 6.0.3 on 2026-07-11 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('recipients', models.JSONField(default=list, verbose_name='Получатели')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлена'), ('failed', 'С ошибками')], default='draft', max_length=16, verbose_name='Статус')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Отправлено')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почтовый ящик')),
                ('display_name', models.CharField(blank=True, max_length=160, verbose_name='Название')),
                ('provider', models.CharField(choices=[('yandex', 'Яндекс'), ('mailru', 'Mail.ru'), ('other', 'Другой')], default='other', max_length=20, verbose_name='Провайдер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('sync_error', models.TextField(blank=True, verbose_name='Ошибка синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to='mailer.client', verbose_name='Клиент')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Почтовый ящик',
                'verbose_name_plural': 'Почтовые ящики',
                'ordering': ('display_name', 'email'),
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uid', models.CharField(max_length=255, verbose_name='UID')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Email отправителя')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(blank=True, default='Без темы', max_length=500, verbose_name='Тема')),
                ('body_text', models.TextField(blank=True, verbose_name='Текст письма')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML письма')),
                ('received_at', models.DateTimeField(verbose_name='Получено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Ответ отправлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailer.mailbox', verbose_name='Почтовый ящик')),
            ],
            options={
                'verbose_name': 'Входящее письмо',
                'verbose_name_plural': 'Входящие письма',
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='Телефон')),
                ('device', models.CharField(max_length=120, verbose_name='Устройство')),
                ('job_title', models.CharField(blank=True, default='Менеджер', max_length=120, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль менеджера',
                'verbose_name_plural': 'Профили менеджеров',
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка')], max_length=16, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='mailer.inboundmessage')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='mailer.mailbox')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='inboundmessage',
            constraint=models.UniqueConstraint(fields=('mailbox', 'external_uid'), name='unique_mailbox_message_uid'),
        ),
    ]
