# Generated by Django 6.0.3 on 2026-07-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_campaign_mailbox_inboundmessage_managerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='IMAP сервер'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='imap_port',
            field=models.PositiveIntegerField(default=993, verbose_name='IMAP порт'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='imap_use_ssl',
            field=models.BooleanField(default=True, verbose_name='IMAP SSL'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='password_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='Зашифрованный пароль приложения'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP сервер'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='smtp_port',
            field=models.PositiveIntegerField(default=465, verbose_name='SMTP порт'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='smtp_use_ssl',
            field=models.BooleanField(default=True, verbose_name='SMTP SSL'),
        ),
    ]
