# Generated by Django 6.0.3 on 2026-07-12 12:00

from django.db import migrations, models


def move_google_notifications(apps, schema_editor):
    InboundMessage = apps.get_model('mailer', 'InboundMessage')
    InboundMessage.objects.filter(
        sender_email__iregex=r'@(accounts\.|notifications\.|calendar\.|drive\.)?google\.com$'
    ).update(category='google')


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_mailbox_imap_host_mailbox_imap_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='category',
            field=models.CharField(choices=[('primary', 'Основные'), ('google', 'Уведомления Google')], db_index=True, default='primary', max_length=20, verbose_name='Папка'),
        ),
        migrations.RunPython(move_google_notifications, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='mailbox',
            name='provider',
            field=models.CharField(choices=[('yandex', 'Яндекс'), ('mailru', 'Mail.ru'), ('gmail', 'Gmail'), ('other', 'Другой')], default='other', max_length=20, verbose_name='Провайдер'),
        ),
    ]
