# Generated by Django 6.0.3 on 2026-07-17 04:18

import django.db.models.deletion
from django.db import migrations, models


def seed_regions_and_assign_mailboxes(apps, schema_editor):
    Region = apps.get_model('mailer', 'Region')
    Mailbox = apps.get_model('mailer', 'Mailbox')
    ManagerProfile = apps.get_model('mailer', 'ManagerProfile')
    regions = (
        ('Ахал', 'Аркадаг'),
        ('Балкан', 'Балканабад'),
        ('Дашогуз', 'Дашогуз'),
        ('Лебап', 'Туркменабад'),
        ('Мары', 'Мары'),
    )
    created = {}
    for name, city in regions:
        created[name], _ = Region.objects.get_or_create(name=name, defaults={'city': city})
    lebap = created['Лебап']
    phones = dict(ManagerProfile.objects.values_list('user_id', 'phone'))
    for mailbox in Mailbox.objects.all().iterator():
        mailbox.region_id = lebap.pk
        if not mailbox.owner_phone:
            mailbox.owner_phone = phones.get(mailbox.manager_id, '')
        mailbox.save(update_fields=('region', 'owner_phone'))


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_campaignattachment_outgoingattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Регион')),
                ('city', models.CharField(max_length=80, verbose_name='Административный центр')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='mailbox',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Телефон ответственного пользователя или устройства.', max_length=32, verbose_name='Владелец телефона'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailboxes', to='mailer.region', verbose_name='Регион'),
        ),
        migrations.RunPython(seed_regions_and_assign_mailboxes, migrations.RunPython.noop),
    ]
