# Generated by Django 6.0.3 on 2026-07-19 10:20

import django.db.models.deletion
from django.db import migrations, models


def assign_existing_managers_to_lebap(apps, schema_editor):
    Region = apps.get_model('mailer', 'Region')
    ManagerProfile = apps.get_model('mailer', 'ManagerProfile')
    lebap = Region.objects.filter(name='Лебап').first()
    if lebap:
        ManagerProfile.objects.filter(city='').update(city=lebap.city, region=lebap)


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_regions_and_mailbox_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_profiles', to='mailer.region', verbose_name='Регион'),
        ),
        migrations.RunPython(assign_existing_managers_to_lebap, migrations.RunPython.noop),
    ]
