# Generated by Django 6.0.3 on 2026-07-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_manager_city_and_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mail/inbound/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, max_length=160, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('part_index', models.PositiveIntegerField(verbose_name='Номер части')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
            ],
            options={
                'ordering': ('part_index',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='inboundmessage',
            name='unique_mailbox_message_uid',
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='attachments_synced',
            field=models.BooleanField(default=False, verbose_name='Вложения обработаны'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='imap_folder',
            field=models.CharField(db_index=True, default='INBOX', max_length=255, verbose_name='IMAP папка'),
        ),
        migrations.AlterField(
            model_name='inboundmessage',
            name='category',
            field=models.CharField(choices=[('primary', 'Основные'), ('google', 'Уведомления Google'), ('spam', 'Спам'), ('sent', 'Отправленные')], db_index=True, default='primary', max_length=20, verbose_name='Папка'),
        ),
        migrations.AddConstraint(
            model_name='inboundmessage',
            constraint=models.UniqueConstraint(fields=('mailbox', 'imap_folder', 'external_uid'), name='unique_mailbox_folder_message_uid'),
        ),
        migrations.AddField(
            model_name='inboundattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailer.inboundmessage'),
        ),
        migrations.AddConstraint(
            model_name='inboundattachment',
            constraint=models.UniqueConstraint(fields=('message', 'part_index'), name='unique_inbound_attachment_part'),
        ),
    ]
