# Generated by Django 6.0.3 on 2026-07-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_inboundattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='telegram_notification_error',
            field=models.TextField(blank=True, verbose_name='Ошибка уведомления Telegram'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='telegram_notification_pending',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Ожидает уведомления Telegram'),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='telegram_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Уведомление Telegram отправлено'),
        ),
    ]
