# Generated by Django 6.0.3 on 2026-07-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_inboundmessage_telegram_notification_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='password_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='Зашифрованный пароль почты'),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='provider',
            field=models.CharField(choices=[('yandex', 'Яндекс'), ('mailru', 'Mail.ru'), ('gmail', 'Gmail'), ('sanly', 'Sanly.tm'), ('other', 'Другой')], default='other', max_length=20, verbose_name='Провайдер'),
        ),
    ]
