# Generated by Django 6.0.3 on 2026-07-27 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_alter_mailbox_password_encrypted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('completed', 'Завершена'), ('failed', 'Ошибка')], db_index=True, default='queued', max_length=20, verbose_name='Статус')),
                ('processed', models.PositiveIntegerField(default=0, verbose_name='Обработано ящиков')),
                ('imported', models.PositiveIntegerField(default=0, verbose_name='Загружено писем')),
                ('errors', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка запуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('manager', models.ForeignKey(blank=True, help_text='Пустое значение означает синхронизацию всех активных ящиков.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_sync_runs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Запуск синхронизации почты',
                'verbose_name_plural': 'Запуски синхронизации почты',
                'ordering': ('-created_at',),
            },
        ),
    ]
