# Generated by Django 6.0.3 on 2026-07-27 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0011_mailboxsyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='telegram_notifications_after',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Уведомлять в Telegram после'),
        ),
    ]
