# Generated by Django 6.0.3 on 2026-07-28 04:38

import django.db.models.deletion
import mailer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0012_mailbox_telegram_notifications_after'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Если выключено, AI-анализ и Telegram-уведомления о новых письмах приостанавливаются.', verbose_name='Включить AI-анализ')),
                ('api_keys_encrypted', models.TextField(blank=True, editable=False, verbose_name='Зашифрованные API-ключи')),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100, verbose_name='Модель Gemini')),
                ('importance_threshold', models.PositiveSmallIntegerField(default=70, help_text='От 0 до 100. Уведомление отправляется только при оценке не ниже порога.', verbose_name='Порог важности для Telegram')),
                ('context_messages', models.PositiveSmallIntegerField(default=5, help_text='Текущее письмо и предыдущие письма от того же домена. Рекомендуется 5.', verbose_name='Писем в контексте')),
                ('max_body_chars', models.PositiveIntegerField(default=12000, help_text='Ограничивает объём текста одного письма, отправляемого на анализ.', verbose_name='Максимум символов письма')),
                ('request_delay_seconds', models.FloatField(default=2.0, help_text='Снижает риск превышения лимита Gemini. Для бесплатного ключа можно увеличить.', verbose_name='Пауза между запросами, сек.')),
                ('custom_instructions', models.TextField(default=mailer.models.default_ai_instructions, verbose_name='Дополнительные правила анализа')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний успешный анализ')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Настройки обновлены')),
            ],
            options={
                'verbose_name': 'Настройки Gemini',
                'verbose_name_plural': 'Настройки Gemini',
            },
        ),
        migrations.CreateModel(
            name='EmailAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Анализируется'), ('completed', 'Готово'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('is_important', models.BooleanField(db_index=True, default=False, verbose_name='Важное')),
                ('importance_score', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Оценка важности')),
                ('is_university', models.BooleanField(db_index=True, default=False, verbose_name='От вуза')),
                ('university_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Вуз')),
                ('university_group', models.CharField(choices=[('medical', 'Медицинские вузы'), ('technical', 'Технические и авиационные вузы'), ('federal', 'Федеральные и классические вузы'), ('other_university', 'Другие вузы'), ('non_university', 'Не вуз')], db_index=True, default='non_university', max_length=30, verbose_name='Группа')),
                ('topic', models.CharField(choices=[('documents', 'Документы'), ('admission', 'Поступление и зачисление'), ('exam', 'Экзамены'), ('personal_account', 'Личный кабинет'), ('payment', 'Оплата'), ('deadline', 'Сроки'), ('security', 'Безопасность'), ('marketing', 'Реклама и рассылка'), ('other', 'Другое')], db_index=True, default='other', max_length=30, verbose_name='Тема AI')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('reason', models.TextField(blank=True, verbose_name='Почему важно или не важно')),
                ('action_required', models.TextField(blank=True, verbose_name='Что нужно сделать')),
                ('deadline', models.CharField(blank=True, max_length=160, verbose_name='Срок')),
                ('extracted_links', models.JSONField(blank=True, default=list, verbose_name='Ссылки')),
                ('extracted_logins', models.JSONField(blank=True, default=list, verbose_name='Логины')),
                ('extracted_passwords', models.JSONField(blank=True, default=list, verbose_name='Пароли и коды')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('analyzed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проанализировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='mailer.inboundmessage', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'AI-анализ письма',
                'verbose_name_plural': 'AI-анализ писем',
                'ordering': ('-message__received_at',),
            },
        ),
    ]
