server {
    listen 0.0.0.0:8011;
    server_name tmmail.ru;
    client_max_body_size 55m;
    allow 127.0.0.1;
    allow 172.16.0.0/12;
    allow 192.168.0.0/16;
    deny all;

    location /static/ {
        alias /opt/smtp_sl/app/staticfiles/;
        expires 7d;
        access_log off;
    }
    location ^~ /media/mail/inbound/ {
        return 404;
    }
    location /media/ {
        alias /opt/smtp_sl/data/media/;
        expires 7d;
        access_log off;
    }
    location / {
        proxy_pass http://127.0.0.1:8010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 120s;
    }
}
