"""
Django settings for smtp_sl project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-)$l&hu@q=9vm(1tif*h0g@u18+gcaxg4lm7qafz@yd_*fjo%z@')
MAILBOX_ENCRYPTION_KEY = os.environ.get('MAILBOX_ENCRYPTION_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1').lower() in {'1', 'true', 'yes'}

if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be changed in production.')
if not DEBUG and not MAILBOX_ENCRYPTION_KEY:
    raise ImproperlyConfigured('MAILBOX_ENCRYPTION_KEY is required in production.')

ALLOWED_HOSTS = [item.strip() for item in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if item.strip()]
CSRF_TRUSTED_ORIGINS = [item.strip() for item in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if item.strip()]


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'background_task',
    'mailer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smtp_sl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Для кастомных шаблонов регистрации
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smtp_sl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH', BASE_DIR / 'db.sqlite3'),
        'OPTIONS': {
            # Mail synchronization can write while another request creates a
            # login session. Give SQLite enough time to serialize those writes.
            'timeout': 30,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = "Asia/Ashgabat"

USE_I18N = True

USE_TZ = True


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.yandex.ru')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '1').lower() in {'1', 'true', 'yes'}
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '0').lower() in {'1', 'true', 'yes'}
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'SMTP_SL <noreply@tmmail.ru>')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '15'))
MAILBOX_IMAP_TIMEOUT = int(os.environ.get('MAILBOX_IMAP_TIMEOUT', '60'))
MAIL_RETENTION_DAYS = int(os.environ.get('MAIL_RETENTION_DAYS', '30'))
AI_ANALYSIS_MAX_AGE_DAYS = int(os.environ.get('AI_ANALYSIS_MAX_AGE_DAYS', '7'))
AI_ANALYSIS_REMOTE_WORKER = os.environ.get('AI_ANALYSIS_REMOTE_WORKER', '0').lower() in {'1', 'true', 'yes'}
AI_WORKER_TOKEN = os.environ.get('AI_WORKER_TOKEN', '').strip()
AI_WORKER_SERVER_URL = os.environ.get('AI_WORKER_SERVER_URL', 'https://tmmail.ru').rstrip('/')
MAILBOX_IMPORT_API_TOKEN = os.environ.get('MAILBOX_IMPORT_API_TOKEN', '').strip()
MAILBOX_IMPORT_ALLOWED_ORIGIN = os.environ.get(
    'MAILBOX_IMPORT_ALLOWED_ORIGIN',
    'https://mail.tmmail.ru',
).rstrip('/')
MAILU_API_BASE_URL = os.environ.get(
    'MAILU_API_BASE_URL',
    'http://127.0.0.1:8088/api/v1',
).rstrip('/')
MAILU_API_TOKEN = os.environ.get('MAILU_API_TOKEN', '').strip()
TMMAIL_PROVISION_API_TOKEN = os.environ.get('TMMAIL_PROVISION_API_TOKEN', '').strip()
TMMAIL_REGISTRY_API_URL = os.environ.get(
    'TMMAIL_REGISTRY_API_URL',
    'https://tmmail.ru/api/v1/mailboxes/',
).strip()
TMMAIL_REGISTRY_ACCOUNT = os.environ.get('TMMAIL_REGISTRY_ACCOUNT', 'tmmail.ru').strip()
TMMAIL_MAILBOX_DOMAIN = os.environ.get('TMMAIL_MAILBOX_DOMAIN', 'tmmail.ru').strip().casefold()
TMMAIL_DEFAULT_QUOTA_BYTES = int(os.environ.get('TMMAIL_DEFAULT_QUOTA_BYTES', '250000000'))
MANAGER_REGISTRATION_ENABLED = os.environ.get('MANAGER_REGISTRATION_ENABLED', '0').lower() in {'1', 'true', 'yes'}
TELEGRAM_NOTIFICATIONS_ENABLED = os.environ.get('TELEGRAM_NOTIFICATIONS_ENABLED', '0').lower() in {'1', 'true', 'yes'}
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '').strip()
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '').strip()
TELEGRAM_CHAT_IDS = os.environ.get('TELEGRAM_CHAT_IDS', '').strip()
TELEGRAM_FORUM_CHAT_ID = os.environ.get('TELEGRAM_FORUM_CHAT_ID', '').strip()
TELEGRAM_FORUM_TOPICS = os.environ.get('TELEGRAM_FORUM_TOPICS', '').strip()
TELEGRAM_SITE_URL = os.environ.get('TELEGRAM_SITE_URL', 'https://tmmail.ru').rstrip('/')
TELEGRAM_API_IP = os.environ.get('TELEGRAM_API_IP', '').strip()
TELEGRAM_NOTIFICATION_MAX_AGE_DAYS = int(os.environ.get('TELEGRAM_NOTIFICATION_MAX_AGE_DAYS', '3'))

# --- НАСТРОЙКИ UNFOLD (ЦВЕТА И ДИЗАЙН) ---
UNFOLD = {
    "SITE_TITLE": "Система рассылок SL",
    "SITE_HEADER": "Mailer Admin",
    "SITE_URL": "/hub/",
    "COLORS": {
        "primary": { # Темно-синий (Navy)
            "50": "#f0f4f8", "100": "#d9e2ec", "200": "#bcccdc", 
            "300": "#9fb3c8", "400": "#829ab1", "500": "#627d98", 
            "600": "#486581", "700": "#334e68", "800": "#243b53", 
            "900": "#102a43",
        },
        "info": { # Акценты - темно-красный (Burgundy)
            "50": "#fce8e8", "100": "#f8caca", "200": "#f29999", 
            "300": "#eb6666", "400": "#e33636", "500": "#cc1414", 
            "600": "#a31010", "700": "#7a0c0c", "800": "#5c0909", 
            "900": "#420404",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Коммуникации",
                "separator": True,
                "collapsible": False,
                "items": [
                    {"title": "Клиенты", "icon": "group", "link": reverse_lazy("admin:mailer_client_changelist")},
                    {"title": "Почтовые ящики", "icon": "mail", "link": reverse_lazy("admin:mailer_mailbox_changelist")},
                    {"title": "Регионы", "icon": "location_on", "link": reverse_lazy("admin:mailer_region_changelist")},
                    {"title": "Входящие письма", "icon": "inbox", "link": reverse_lazy("admin:mailer_inboundmessage_changelist")},
                    {"title": "Рассылки", "icon": "send", "link": reverse_lazy("admin:mailer_newsletter_changelist")},
                    {"title": "Логи отправки", "icon": "receipt_long", "link": reverse_lazy("admin:mailer_sendinglog_changelist")},
                ],
            },
            {
                "title": "Доступ",
                "separator": True,
                "collapsible": False,
                "items": [
                    {"title": "Менеджеры", "icon": "badge", "link": reverse_lazy("admin:mailer_managerprofile_changelist")},
                    {"title": "Пользователи", "icon": "manage_accounts", "link": reverse_lazy("admin:auth_user_changelist")},
                    {"title": "Группы", "icon": "groups", "link": reverse_lazy("admin:auth_group_changelist")},
                ],
            },
        ],
    },
}

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', '0').lower() in {'1', 'true', 'yes'}
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/hub/'
LOGOUT_REDIRECT_URL = '/login/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'mailer': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
